version: 0.1.{build}
image:
  - Visual Studio 2019
  - Ubuntu
clone_depth: 1
matrix:
  fast_finish: true
install:
  - pwsh: ./scripts/ci-install.ps1
build_script:
  - pwsh: ./scripts/ci-build.ps1
after_build:
  - pwsh: ./scripts/ci-after_build.ps1
test: false
